import { montserrat } from "@/helpers/fonts";
import "@/styles/index.scss";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body >{children}</body>
    </html>
  );
}
